name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: |
          node --version || echo "Node.js is not installed"

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Print MongoDB Version
        run: |
          mongod --version || echo "MongoDB is not installed"
