name: JSON Linter

on:
  push:
    branches:
      - main 

jobs:
  json_linter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jsonlint-cli
        run: npm install -g jsonlint-cli

      - name: Run JSON Linter
        run: jsonlint-cli "$GITHUB_WORKSPACE/DataSchema.json"


